### ISSUE TITLE
Sequence Model

### ISSUE THREAD

**Issue by NguyenQuanAnhMinh** [JudasDie/deeplearning.ai#5]
When you update fully sequence model? thank you

**Comment by JudasDie** [comment]
@NguyenQuanAnhMinh 
Maybe a few days layter, I just found Andrew has released the fifth course.

**Comment by NguyenQuanAnhMinh** [comment]
worth the wait :)

**Comment by hurun** [comment]
could you update the week1 files of sequence model?

**Comment by JudasDie** [comment]
@hurun You mean support files made by Andrew?

**Comment by hurun** [comment]
yes,

**Comment by JudasDie** [comment]
@hurun  You can do your work on Coursera, why bother to download to local PC? (PS: I didn't download these files)

**Comment by hurun** [comment]
sorry,i am in china, a student,not have visva card to register.

**Comment by JudasDie** [comment]
@hurun  Since you are a chinese, i would say, 大兄弟我也是啊。 不用Visa注册，你选择旁听就好了，可以做题
